// src/config.ts
export const RETRIEVAL_CONFIG = {
  SIMILARITY_THRESHOLD: 0.75,
  CONFIDENCE_THRESHOLD: 0.5,
  MAX_CONTEXT_AGE: 5,
  MIN_SIMILARITY_FOR_ANSWER: 0.6,
  MAX_RETRIEVAL_HISTORY: 5,
};

export const REDIS_TTL = 3600; // 1 hour
